trait Jacobi(ImplicitlyCopyable):
    # Three dots indicate that the method is not implemented
    fn initialize_temperature(self): ...
    fn apply_boundary_conditions(self, T: UnsafePointer[Scalar[DType.float64]]): ...
    fn jacobi_update(self): ...
    fn residual_norm(self) -> Float64: ...
    fn solve(var self) -> Int: ...
    