trait Jacobi(ImplicitlyCopyable):
    # Three dots indicate that the method is not implemented
    fn __getitem__(self, i: Int, j: Int) -> Float64: ...
    fn initialize_temperature(self): ...
    fn apply_boundary_conditions(self, T: UnsafePointer[mut=True, Scalar[DType.float64], MutOrigin.external]): ...
    fn jacobi_update(self): ...
    fn residual_norm(self) -> Float64: ...
    fn solve(var self) -> Int: ...
    